### ISSUE TITLE
Windows installation error

### ISSUE THREAD

**Issue by fowse2020** [LinuxSuRen/audacity-label-plugin#3]
As shown below
![eer0](https://user-images.githubusercontent.com/59159039/169435646-ef262479-5222-4d53-ba13-0f49e2e54391.png)
![eer1](https://user-images.githubusercontent.com/59159039/169435663-948db509-260f-46fa-82d0-ad50d038f5f1.png)
Microsoft Windows [10.0.19044.1682]

**Comment by LinuxSuRen** [comment]
It works for me. See also

* Windows 11 家庭中文版
* Audacity 3.1.3

![image](https://user-images.githubusercontent.com/1450685/169441796-dd70b349-dca1-4790-b087-efbf53462766.png)

hi @fowse2020 please make sure you directly save the plugin file from https://raw.githubusercontent.com/LinuxSuRen/audacity-label-plugin/master/label.ny

Or, I have uploaded it as a release asset. See also https://github.com/LinuxSuRen/audacity-label-plugin/releases/tag/v0.1.0

**Comment by fowse2020** [comment]
There may be a problem with the downloaded file. After I saved the content with notepad to the file, it was successfully installed.
Please close this issue
